<?php
namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class Products extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id'          => 1,
                'name'        => 'The Coffee House Sữa Nóng',
                'description' => 'Thức uống giúp tỉnh táo tức thì để bắt đầu ngày mới thật hứng khởi. Không đắng khét như cà phê truyền thống, The Coffee House Sữa Đá mang hương vị hài hoà đầy lôi cuốn. Là sự đậm đà của 100% cà phê Arabica Cầu Đất rang vừa tới, biến tấu tinh tế với sữa đặc và kem sữa ngọt ngào cực quyến rũ. Càng hấp dẫn hơn với topping thạch 100% cà phê nguyên chất giúp giữ trọn vị ngon đến ngụm cuối cùng.',
                'price'       => 39000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1696220170_phin-sua-tuoi-banh-flan_0172beb85d08408b8912bf5f1dae7fd9_large.jpg',
                'category_id' => 9,
                'active'      => true,
                'created_at'  => '2023-05-18 22:03:50',
                'updated_at'  => '2023-05-18 22:03:50',
            ],
            [
                'id'          => 2,
                'name'        => 'The Coffee House Sữa Đá',
                'description' => 'Thức uống giúp tỉnh táo tức thì để bắt đầu ngày mới thật hứng khởi. Không đắng khét như cà phê truyền thống, The Coffee House Sữa Đá mang hương vị hài hoà đầy lôi cuốn. Là sự đậm đà của 100% cà phê Arabica Cầu Đất rang vừa tới, biến tấu tinh tế với sữa đặc và kem sữa ngọt ngào cực quyến rũ. Càng hấp dẫn hơn với topping thạch 100% cà phê nguyên chất giúp giữ trọn vị ngon đến ngụm cuối cùng.',
                'price'       => 39000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1696220170_phin-sua-tuoi-banh-flan_0172beb85d08408b8912bf5f1dae7fd9_large.jpg',
                'category_id' => 9,
                'active'      => true,
                'created_at'  => '2023-05-18 22:03:50',
                'updated_at'  => '2023-05-18 22:03:50',
            ],
            [
                'id'          => 3,
                'name'        => 'Cà Phê Sữa Đá',
                'description' => 'Cà phê Đắk Lắk nguyên chất được pha phin truyền thống kết hợp với sữa đặc tạo nên hương vị đậm đà, hài hòa giữa vị ngọt đầu lưỡi và vị đắng thanh thoát nơi hậu vị.',
                'price'       => 29000,
                'price_sale'  => 0,
                'image_url'   => 'https://minio.thecoffeehouse.com/image/admin/1737357012_cfsd_400x400.png',
                'category_id' => 9,
                'active'      => true,
                'created_at'  => '2023-05-18 22:14:24',
                'updated_at'  => '2023-05-18 22:14:24',
            ],
            [
                'id'          => 4,
                'name'        => 'Bạc Sỉu',
                'description' => 'Bạc sỉu chính là "Ly sữa trắng kèm một chút cà phê". Thức uống này rất phù hợp những ai vừa muốn trải nghiệm chút vị đắng của cà phê vừa muốn thưởng thức vị ngọt béo ngậy từ sữa.',
                'price'       => 29000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1639377904_bac-siu_525b9fa5055b41f183088c8e479a9472_large.jpg',
                'category_id' => 9,
                'active'      => true,
                'created_at'  => '2023-05-18 22:15:24',
                'updated_at'  => '2023-05-18 22:15:24',
            ],
            [
                'id'          => 5,
                'name'        => 'Cà Phê Đen Đá',
                'description' => 'Không ngọt ngào như Bạc sỉu hay Cà phê sữa, Cà phê đen mang trong mình phong vị trầm lắng, thi vị hơn. Người ta thường phải ngồi rất lâu mới cảm nhận được hết hương thơm ngào ngạt, phảng phất mùi cacao và cái đắng mượt mà trôi tuột xuống vòm họng.',
                'price'       => 29000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1639377797_ca-phe-den-da_6f4766ec0f8b4e929a8d916ae3c13254_large.jpg',
                'category_id' => 9,
                'active'      => true,
                'created_at'  => '2023-05-18 22:16:51',
                'updated_at'  => '2023-05-18 22:16:51',
            ],
            [
                'id'          => 6,
                'name'        => 'Cà Phê Sữa Nóng',
                'description' => 'Cà phê được pha phin truyền thống kết hợp với sữa đặc tạo nên hương vị đậm đà, hài hòa giữa vị ngọt đầu lưỡi và vị đắng thanh thoát nơi hậu vị.',
                'price'       => 39000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737356996_cfs-nong_b67f6d43e52948209dee212446981bb5_large.png',
                'category_id' => 9,
                'active'      => true,
                'created_at'  => '2023-05-18 22:17:50',
                'updated_at'  => '2023-05-18 22:18:29',
            ],
            [
                'id'          => 7,
                'name'        => 'Đường Đen Marble Latte',
                'description' => '- Sản phẩm không thể thay đổi độ ngọt - Khuấy đều trước khi sử dụng Đường Đen Marble Latte êm dịu cực hấp dẫn bởi vị cà phê đắng nhẹ hoà quyện cùng vị đường đen ngọt thơm và sữa tươi béo mịn. Sự kết hợp đầy mới mẻ của cà phê và đường đen cũng tạo nên diện mạo phân tầng đẹp mắt. Đây là lựa chọn đáng thử để bạn khởi đầu ngày mới đầy hứng khởi.',
                'price'       => 55000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1686716537_dd-latte_785591205184481597a2a79b9331e03b_large.jpg',
                'category_id' => 10,
                'active'      => true,
                'created_at'  => '2023-05-18 22:19:27',
                'updated_at'  => '2023-05-18 22:19:27',
            ],
            [
                'id'          => 8,
                'name'        => 'Caramel Macchiato Đá',
                'description' => 'Khuấy đều trước khi sử dụng Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.',
                'price'       => 55000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737357135_caramel-macchiato-da_d0a3250162e6427ab8808d8bc35012ec_large.png',
                'category_id' => 10,
                'active'      => true,
                'created_at'  => '2023-05-18 22:20:12',
                'updated_at'  => '2023-05-18 22:20:12',
            ],
            [
                'id'          => 9,
                'name'        => 'Caramel Macchiato Nóng',
                'description' => 'Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.',
                'price'       => 55000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737357126_caramel-macchiato-nong_92ab6d4b88dc4842b42c0ee6ad523392_large.png',
                'category_id' => 10,
                'active'      => true,
                'created_at'  => '2023-05-18 22:20:59',
                'updated_at'  => '2023-05-18 22:20:59',
            ],
            [
                'id'          => 10,
                'name'        => 'Latte Đá',
                'description' => 'Một sự kết hợp tinh tế giữa vị đắng cà phê Espresso nguyên chất hòa quyện cùng vị sữa nóng ngọt ngào, bên trên là một lớp kem mỏng nhẹ tạo nên một tách cà phê hoàn hảo về hương vị lẫn nhãn quan.',
                'price'       => 55000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/latte-da_438410_ff2be8d76067434385f8e27b33fed780_large.jpg',
                'category_id' => 10,
                'active'      => true,
                'created_at'  => '2023-05-18 22:22:11',
                'updated_at'  => '2023-05-18 22:22:11',
            ],
            [
                'id'          => 11,
                'name'        => 'Cold Brew Phúc Bồn Tử',
                'description' => 'Vị chua ngọt của trái phúc bồn tử, làm dậy lên hương vị trái cây tự nhiên vốn sẵn có trong hạt cà phê, hòa quyện thêm vị đăng đắng, ngọt dịu nhẹ nhàng của Cold Brew 100% hạt Arabica Cầu Đất để mang đến một cách thưởng thức cà phê hoàn toàn mới, vừa thơm lừng hương cà phê quen thuộc, vừa nhẹ nhàng và thanh mát bởi hương trái cây đầy thú vị.',
                'price'       => 49000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1675329120_coldbrew-pbt_127e09b0000c4027992bc3168899a656_large.jpg',
                'category_id' => 15,
                'active'      => true,
                'created_at'  => '2023-05-18 22:23:27',
                'updated_at'  => '2023-05-18 22:23:27',
            ],
            [
                'id'          => 12,
                'name'        => 'Cold Brew Sữa Tươi',
                'description' => 'Thanh mát và cân bằng với hương vị cà phê nguyên bản 100% Arabica Cầu Đất cùng sữa tươi thơm béo cho từng ngụm tròn vị, hấp dẫn.',
                'price'       => 49000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/cold-brew-sua-tuoi_379576_990956a1473e4ded82c8f76b877b7d15_large.jpg',
                'category_id' => 15,
                'active'      => true,
                'created_at'  => '2023-05-18 22:24:22',
                'updated_at'  => '2023-05-18 22:24:22',
            ],
            [
                'id'          => 13,
                'name'        => 'CloudFee Hạnh Nhân Nướng',
                'description' => 'Vị đắng nhẹ từ cà phê phin truyền thống kết hợp Espresso Ý, lẫn chút ngọt ngào của kem sữa và lớp foam trứng cacao, nhấn thêm hạnh nhân nướng thơm bùi, kèm topping thạch cà phê dai giòn mê ly. Tất cả cùng quyện hoà trong một thức uống làm vị giác "thức giấc", thơm ngon hết nấc.',
                'price'       => 49000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1697442235_cloudfee-hanh-nhan-nuong_5bb2e4932e664cd5adfa9a48d0551ced_large.jpg',
                'category_id' => 2,
                'active'      => true,
                'created_at'  => '2023-05-18 22:25:36',
                'updated_at'  => '2023-05-18 22:25:36',
            ],
            [
                'id'          => 14,
                'name'        => 'CloudFee Caramel',
                'description' => 'Ngon khó cưỡng bởi xíu đắng nhẹ từ cà phê phin truyền thống pha trộn với Espresso lừng danh nước Ý, quyện vị kem sữa và caramel ngọt ngọt, thêm lớp foam trứng cacao bồng bềnh béo mịn, kèm topping thạch cà phê dai giòn nhai cực cuốn. Một thức uống "điểm mười" cho cả ngày tươi không cần tưới.',
                'price'       => 49000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1700837665_tra-sua-tra-xanh-tay-bac-ly-thuy-tinh_0bbbce94b73147998da49263f896a224_large.jpg',
                'category_id' => 2,
                'active'      => true,
                'created_at'  => '2023-05-18 22:26:18',
                'updated_at'  => '2023-05-18 22:26:18',
            ],
            [
                'id'          => 15,
                'name'        => 'CloudFee Hà Nội',
                'description' => 'Khiến bạn mê mẩn ngay ngụm đầu tiên bởi vị đắng nhẹ của cà phê phin truyền thống kết hợp Espresso Ý, quyện hòa cùng chút ngọt ngào của kem sữa, và thơm béo từ foam trứng cacao. Nhấp một ngụm rồi nhai cùng thạch cà phê dai dai giòn giòn, đúng chuẩn "ngon quên lối về". CloudFee Classic là món đậm vị cà phê nhất trong bộ sưu tập nhưng không quá đắng, ngậy nhưng không hề ngấy.',
                'price'       => 49000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1700837685_tra-sua-oolong-berry-ly-thuy-tinh_34e677396c5649e993aab4fc99f61800_large.jpg',
                'category_id' => 2,
                'active'      => true,
                'created_at'  => '2023-05-18 22:27:04',
                'updated_at'  => '2023-05-18 22:27:04',
            ],
            [
                'id'          => 16,
                'name'        => 'CloudTea Oolong Nướng Kem Cheese',
                'description' => 'Hội mê cheese sao có thể bỏ lỡ chiếc trà sữa siêu mlem này. Món đậm vị Oolong nướng - nền trà được yêu thích nhất hiện nay, quyện thêm kem sữa thơm béo. Đặc biệt, chinh phục ngay fan ghiền cheese bởi lớp foam phô mai mềm tan mằn mặn. Càng ngon cực với thạch Oolong nướng nguyên chất giòn dai nhai siêu thích.',
                'price'       => 55000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1686716517_kombucha-dao_e44faddaa4ba407986849be42ef78b76_large.jpg',
                'category_id' => 3,
                'active'      => true,
                'created_at'  => '2023-05-18 22:28:14',
                'updated_at'  => '2023-05-18 22:28:14',
            ],
            [
                'id'          => 17,
                'name'        => 'CloudTea Oolong Nướng Caramel',
                'description' => 'Chiếc trà sữa chân ái dành cho tín đồ hảo ngọt gọi tên CloudTea Oolong Nướng Caramel. Sự kết hợp của foam trứng béo mịn, caramel thơm lừng, trà Oolong nướng rõ vị quyện kem sữa ngọt ngào, làm tan chảy vị giác tựa khoảnh khắc chạm môi người thương. Thêm bột cacao đậm đà và thạch Oolong nướng dai giòn giúp độ ngon nhân đôi.',
                'price'       => 55000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1675355728_cheese_034169ff66af44209a4fb9362b8f439e_large.jpg',
                'category_id' => 3,
                'active'      => true,
                'created_at'  => '2023-05-18 22:29:01',
                'updated_at'  => '2023-05-18 22:29:01',
            ],
            [
                'id'          => 18,
                'name'        => 'CloudTea Oolong Nướng Kem Dừa Đá Xay',
                'description' => 'Trà sữa đá xay - phiên bản nâng cấp đầy mới lạ của trà sữa truyền thống, lần đầu xuất hiện tại Nhà. Ngon khó cưỡng với lớp kem dừa béo ngậy nhưng không ngấy, thêm vụn bánh quy phô mai giòn tan vui miệng. Trà Oolong nướng rõ hương đậm vị, quyện với sữa dừa beo béo, được xay mịn cùng đá, mát rượi trong tích tắc. Đặc biệt, thạch Oolong nướng nguyên chất giúp giữ trọn vị đậm đà của trà sữa đến giọt cuối cùng.',
                'price'       => 55000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1675355728_cheese_034169ff66af44209a4fb9362b8f439e_large.jpg',
                'category_id' => 3,
                'active'      => true,
                'created_at'  => '2023-05-18 22:29:51',
                'updated_at'  => '2023-05-18 22:29:51',
            ],
            [
                'id'          => 19,
                'name'        => 'Trà Long Nhãn Hạt Sen',
                'description' => 'Thức uống mang hương vị của nhãn, của sen, của trà Oolong đầy thanh mát cho tất cả các thành viên trong dịp Tết này. An lành, thư thái và đậm đà chính là những gì The Coffee House mong muốn gửi trao đến bạn và gia đình.',
                'price'       => 49000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1649378747_tra-sen-nhan_441ab034e29e4858813ebff91f85162d_large.jpg',
                'category_id' => 11,
                'active'      => true,
                'created_at'  => '2023-05-18 22:33:53',
                'updated_at'  => '2023-05-18 22:33:53',
            ],
            [
                'id'          => 20,
                'name'        => 'Trà Đào Cam Sả Đá',
                'description' => 'Vị thanh ngọt của đào, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này.',
                'price'       => 49000,
                'price_sale'  => 0,
                'image_url'   => 'https://minio.thecoffeehouse.com/image/admin/1737356280_tra-dao-cam-sa_400x400.png',
                'category_id' => 11,
                'active'      => true,
                'created_at'  => '2023-05-18 22:34:38',
                'updated_at'  => '2023-05-18 22:34:38',
            ],
            [
                'id'          => 21,
                'name'        => 'Trà Đào Cam Sả Đá Chai Fresh 500ML',
                'description' => 'Với phiên bản chai fresh 500ml, thức uống "best seller" đỉnh cao mang một diện mạo tươi mới, tiện lợi, phù hợp với bình thường mới và vẫn giữ nguyên vị thanh ngọt của đào, vị chua dịu của cam vàng nguyên vỏ và vị trà đen thơm lừng ly Trà đào cam sả nguyên bản. *Sản phẩm dùng ngon nhất trong ngày. *Sản phẩm mặc định mức đường và không đá.',
                'price'       => 105000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/bottle_tradao_836487_26e2fa52f31b4822a6f2c706a77d75f1_large.jpg',
                'category_id' => 11,
                'active'      => true,
                'created_at'  => '2023-05-18 22:35:47',
                'updated_at'  => '2023-05-18 22:35:47',
            ],
            [
                'id'          => 22,
                'name'        => 'Trà Đen Macchiato',
                'description' => 'Trà đen được ủ mới mỗi ngày, giữ nguyên được vị chát mạnh mẽ đặc trưng của lá trà, phủ bên trên là lớp Macchiato "homemade" bồng bềnh quyến rũ vị phô mai mặn mặn mà béo béo.',
                'price'       => 55000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/tra-den-matchiato_430281_5d57903f55e745d4b547adbfe75b4e8d_large.jpg',
                'category_id' => 12,
                'active'      => true,
                'created_at'  => '2023-05-18 22:36:46',
                'updated_at'  => '2023-05-18 22:36:46',
            ],
            [
                'id'          => 23,
                'name'        => 'Trà sữa Oolong Nướng Trân Châu',
                'description' => 'Hương vị chân ái đúng gu đậm đà với trà oolong được "sao" (nướng) lâu hơn cho hương vị đậm đà, hòa quyện với sữa thơm béo mang đến cảm giác mát lạnh, lưu luyến vị trà sữa đậm đà nơi vòm họng.',
                'price'       => 55000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1669736877_tra-sua-oolong-nuong-tran-chau_0e1cad07ca1846819f27cb2a60da7e60_large.png',
                'category_id' => 12,
                'active'      => true,
                'created_at'  => '2023-05-18 22:37:31',
                'updated_at'  => '2023-05-18 22:37:31',
            ],
            [
                'id'          => 24,
                'name'        => 'Hi Tea Vải',
                'description' => 'Chút ngọt ngào của Vải, mix cùng vị chua thanh tao từ trà hoa Hibiscus, mang đến cho bạn thức uống đúng chuẩn vừa ngon, vừa healthy.',
                'price'       => 49000,
                'price_sale'  => 0,
                'image_url'   => 'https://minio.thecoffeehouse.com/image/admin/1737356461_hi-tea-vai_400x400.png',
                'category_id' => 20,
                'active'      => true,
                'created_at'  => '2023-05-18 22:39:05',
                'updated_at'  => '2023-05-18 22:39:05',
            ],
            [
                'id'          => 25,
                'name'        => 'Hi Tea Yuzu Trân Châu',
                'description' => 'Không chỉ nổi bật với sắc đỏ đặc trưng từ trà hoa Hibiscus, Hi-Tea Yuzu còn gây ấn tượng với topping Yuzu (quýt Nhật) lạ miệng, kết hợp cùng trân châu trắng dai giòn sần sật, nhai vui vui.',
                'price'       => 49000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1669736859_hi-tea-yuzu-tran-chau_7f262a6128b64bcb898e2c6e05706c57_large.png',
                'category_id' => 20,
                'active'      => true,
                'created_at'  => '2023-05-18 22:40:35',
                'updated_at'  => '2023-05-18 22:40:35',
            ],
            [
                'id'          => 26,
                'name'        => 'Hi Tea Đào Kombucha',
                'description' => 'Trà hoa Hibiscus 0% caffeine chua nhẹ, kết hợp cùng trà lên men Kombucha hoàn toàn tự nhiên và Đào thanh mát tạo nên Hi-Tea Đào Kombucha chua ngọt cực cuốn. Đặc biệt Kombucha Detox giàu axit hữu cơ, Đào nhiều chất xơ giúp thanh lọc cơ thể và hỗ trợ giảm cân hiệu quả. Lưu ý: Khuấy đều trước khi dùng',
                'price'       => 59000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1686716517_kombucha-dao_e44faddaa4ba407986849be42ef78b76_large.jpg',
                'category_id' => 20,
                'active'      => true,
                'created_at'  => '2023-05-18 22:41:23',
                'updated_at'  => '2023-05-18 22:41:23',
            ],
            [
                'id'          => 27,
                'name'        => 'Bánh Mì VN Thịt Nguội',
                'description' => 'Gói gọn trong ổ bánh mì Việt Nam là từng lớp chả, từng lớp jambon hòa quyện cùng bơ và pate thơm lừng, thêm dưa rau cho bữa sáng đầy năng lượng. *Phần bánh sẽ ngon và đậm đà nhất khi kèm pate. Để đảm bảo hương vị được trọn vẹn, Nhà mong bạn thông cảm vì không thể thay đổi định lượng pate.',
                'price'       => 35000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1638440015_banh-mi-vietnam_beac1109d4df428a85d224302c326fd9_large.jpg',
                'category_id' => 13,
                'active'      => true,
                'created_at'  => '2023-05-18 22:44:45',
                'updated_at'  => '2023-05-18 22:44:45',
            ],
            [
                'id'          => 28,
                'name'        => 'Chà Bông Phô Mai',
                'description' => 'Chiếc bánh với lớp phô mai vàng sánh mịn bên trong, được bọc ngoài lớp vỏ xốp mềm thơm lừng. Thêm lớp chà bông mằn mặn hấp dẫn bên trên.',
                'price'       => 35000,
                'price_sale'  => 0,
                'image_url'   => 'https://minio.thecoffeehouse.com/image/admin/1737355233_bami-cha-bong-pho-mai_400x400.png',
                'category_id' => 13,
                'active'      => true,
                'created_at'  => '2023-05-18 22:45:43',
                'updated_at'  => '2023-05-18 22:45:43',
            ],
            [
                'id'          => 29,
                'name'        => 'Hi Tea Đá Tuyết Yuzu Vải',
                'description' => 'Vị trà hoa Hibiscus chua chua, kết hợp cùng đá tuyết Yuzu mát lạnh tái tê, thêm miếng vải căng mọng, ngọt ngào sẽ khiến bạn thích thú ngay từ lần thử đầu tiên.',
                'price'       => 59000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1669736859_hi-tea-yuzu-tran-chau_7f262a6128b64bcb898e2c6e05706c57_large.png',
                'category_id' => 21,
                'active'      => true,
                'created_at'  => '2023-05-18 22:47:05',
                'updated_at'  => '2023-05-18 22:47:05',
            ],
            [
                'id'          => 30,
                'name'        => 'Mochi Kem Chocolate',
                'description' => 'Bao bọc bởi lớp vỏ Mochi dẻo thơm, bên trong là lớp kem lạnh cùng nhân chocolate độc đáo. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.',
                'price'       => 19000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1643102019_mochi-phucbontu_468fa88cdb01487799ba8ec43f6f9bbf_large.jpg',
                'category_id' => 16,
                'active'      => true,
                'created_at'  => '2023-05-18 22:47:57',
                'updated_at'  => '2023-05-18 22:47:57',
            ],
            [
                'id'          => 31,
                'name'        => 'Mousse Gấu Chocolate',
                'description' => 'Với vẻ ngoài đáng yêu và hương vị ngọt ngào, thơm béo nhất định bạn phải thử ít nhất 1 lần.',
                'price'       => 39000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737355325_mouse-gau-choco_5955c2483e1c47ad923d5fb402aa038e_large.png',
                'category_id' => 16,
                'active'      => true,
                'created_at'  => '2023-05-18 22:48:52',
                'updated_at'  => '2023-05-18 22:48:52',
            ],
            [
                'id'          => 32,
                'name'        => 'Mít',
                'description' => 'Mít sấy khô vàng ươm, giòn rụm, giữ nguyên được vị ngọt lịm của mít tươi.',
                'price'       => 20000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/mit-say_666228_173b91aa45064ac0911c5ec4ceb5b519_large.jpg',
                'category_id' => 14,
                'active'      => true,
                'created_at'  => '2023-05-18 22:49:56',
                'updated_at'  => '2023-05-18 22:49:56',
            ],
            [
                'id'          => 33,
                'name'        => 'Gà Xé Lá Chanh',
                'description' => 'Thịt gà được xé tơi, mang hương vị mặn, ngọt, cay cay quyện nhau vừa chuẩn, thêm chút thơm thơm thơm từ lá chanh sấy khô giòn giòn xua tan ngay cơn buồn miệng.',
                'price'       => 25000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/kho-ga-la-chanh_995862_da70fe58aa6e4d1497cfd88d8612b0de_large.jpg',
                'category_id' => 14,
                'active'      => true,
                'created_at'  => '2023-05-18 22:50:46',
                'updated_at'  => '2023-05-18 22:50:46',
            ],
            [
                'id'          => 34,
                'name'        => 'Thùng Cà Phê Sữa Espresso',
                'description' => 'Được sản xuất theo công nghệ Nhật, Cà Phê Sữa Espresso The Coffee House giữ trọn hương vị đậm đà của 100% cà phê Robusta nguyên chất quyện hoà cùng sữa béo thơm lừng. Bật nắp trải nghiệm ngay chất cà phê mạnh mẽ giúp sảng khoái tức thì, tuôn trào hứng khởi',
                'price'       => 336000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1669707271_24lon-espresso-no_ed306dbf99a04bb0ae91750a976828bb_large.jpg',
                'category_id' => 17,
                'active'      => true,
                'created_at'  => '2023-05-18 22:52:03',
                'updated_at'  => '2023-05-18 22:52:03',
            ],
            [
                'id'          => 35,
                'name'        => 'Trà Vị Đào Tearoma 14x14g',
                'description' => 'Được chiết xuất từ 100% trà tự nhiên, không phẩm màu tổng hợp, Trà vị Đào Tearoma mang đến cảm giác thanh mát cực đã. Nhấp một ngụm, cảm nhận trọn vị đào chua ngọt thơm ngon bùng nổ. Ngoài ra, trà còn bổ sung vitamin C cực kỳ có lợi cho sức khoẻ.',
                'price'       => 32000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1669706771_bg-tradao-min_28c767bc07194739999efe07f15e8ad6_large.jpg',
                'category_id' => 18,
                'active'      => true,
                'created_at'  => '2023-05-18 22:52:52',
                'updated_at'  => '2023-05-18 22:52:52',
            ],
            [
                'id'          => 36,
                'name'        => 'Chocolate Đá',
                'description' => 'Bột chocolate nguyên chất hoà cùng sữa tươi béo ngậy, ấm nóng. Vị ngọt tự nhiên, không gắt cổ, để lại một chút đắng nhẹ, cay cay trên đầu lưỡi.',
                'price'       => 55000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1697441952_choco-chip_06433e0e342b40d7bc59391be6df4c84_large.png',
                'category_id' => 19,
                'active'      => true,
                'created_at'  => '2023-05-18 22:53:47',
                'updated_at'  => '2023-05-18 22:53:47',
            ],
            [
                'id'          => 37,
                'name'        => 'Croissant trứng muối',
                'description' => 'Croissant trứng muối thơm lừng, bên ngoài vỏ bánh giòn hấp dẫn bên trong trứng muối vị ngon khó cưỡng.',
                'price'       => 35000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/croissant-trung-muoi_880850_83d055b927ce4515ad362e8126073f76_large.jpg',
                'category_id' => 13,
                'active'      => true,
                'created_at'  => '2023-05-18 23:57:30',
                'updated_at'  => '2023-05-18 23:57:30',
            ],
            [
                'id'          => 38,
                'name'        => 'Bánh Mì Gậy Gà Kim Quất',
                'description' => 'Phiên bản nâng cấp với trọng lượng tăng 80% so với bánh mì que thông thường, đem đến cho bạn bữa ăn nhanh gọn mà vẫn đầy đủ dinh dưỡng. Cắn một miếng là mê mẩn bởi vỏ bánh nướng giòn rụm, nhân đậm vị với từng miếng thịt gà mềm, ướp sốt kim quất chua ngọt, thơm nức đặc trưng. Càng "đúng bài" hơn khi thưởng thức kèm Cà phê đượm vị hoặc trà Hi-Tea thanh mát.',
                'price'       => 25000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1669737009_banh-mi-gay-ga-kim-quat_3733b6b591d7472391549b2e9da15d16_large.png',
                'category_id' => 13,
                'active'      => true,
                'created_at'  => '2023-05-19 01:12:39',
                'updated_at'  => '2023-05-19 01:12:39',
            ],
            [
                'id'          => 39,
                'name'        => 'Bánh Mì Gậy Cá Ngừ Mayo',
                'description' => 'Trọng lượng tăng 70% so với bánh mì que thông thường, thêm nhiều dinh dưỡng, thích hợp cho cả bữa ăn nhẹ lẫn ăn no. Ngon hết chỗ chê từ vỏ bánh nướng nóng giòn, cá ngừ đậm đà quyện lẫn sốt mayo thơm béo đến từng hạt bắp ngọt bùi hấp dẫn. Nhâm nhi bánh cùng ly Cà phê thơm nồng hay Hi-Tea tươi mát thì đúng chuẩn "điểm mười".',
                'price'       => 25000,
                'price_sale'  => 0,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1669737009_banh-mi-gay-ga-kim-quat_3733b6b591d7472391549b2e9da15d16_large.png',
                'category_id' => 13,
                'active'      => true,
                'created_at'  => '2023-05-19 01:25:03',
                'updated_at'  => '2023-05-19 01:25:03',
            ],
            [
                'id'          => 40,
                'name'        => 'Cà Phê Đen Nóng',
                'description' => 'Không ngọt ngào như Bạc sỉu hay Cà phê sữa, Cà phê đen mang trong mình phong vị trầm lắng, thi vị hơn. Người ta thường phải ngồi rất lâu mới cảm nhận được hết hương thơm ngào ngạt, phảng phất mùi cacao và cái đắng mượt mà trôi tuột xuống vòm họng.',
                'price'       => 39000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737356979_cf-den-nong_3ce91ffbdc04405b93855cd3b5d5aec2.png',
                'category_id' => 9,
                'active'      => true,
                'created_at'  => '2025-06-09 08:26:58',
                'updated_at'  => '2025-06-09 08:26:58',
            ],
            [
                'id'          => 41,
                'name'        => 'Americano Nóng',
                'description' => 'Americano được pha chế bằng cách pha thêm nước với tỷ lệ nhất định vào tách cà phê Espresso, từ đó mang lại hương vị nhẹ nhàng và giữ trọn được mùi hương cà phê đặc trưng.',
                'price'       => 49000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737357102_ame-nong_2988095b141f4f5a8e0eb40be3b43ba6.png',
                'category_id' => 10,
                'active'      => true,
                'created_at'  => '2025-06-09 08:28:38',
                'updated_at'  => '2025-06-09 08:28:38',
            ],
            [
                'id'          => 42,
                'name'        => 'Cappuccino Nóng',
                'description' => 'Capuchino là thức uống hòa quyện giữa hương thơm của sữa, vị béo của bọt kem cùng vị đậm đà từ cà phê Espresso. Tất cả tạo nên một hương vị đặc biệt, một chút nhẹ nhàng, trầm lắng và tinh tế.',
                'price'       => 55000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737357108_cappucino-nong_f78c106928fe4c418906763d3dfa4b29.png',
                'category_id' => 10,
                'active'      => true,
                'created_at'  => '2025-06-09 08:29:52',
                'updated_at'  => '2025-06-09 08:29:52',
            ],
            [
                'id'          => 43,
                'name'        => 'Cappuccino Đá',
                'description' => 'Capuchino là thức uống hòa quyện giữa hương thơm của sữa, vị béo của bọt kem cùng vị đậm đà từ cà phê Espresso. Tất cả tạo nên một hương vị đặc biệt, một chút nhẹ nhàng, trầm lắng và tinh tế.',
                'price'       => 55000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737357118_cappucio-da_9adfe1f331a348068d265e7ce3f5d35e.png',
                'category_id' => 10,
                'active'      => true,
                'created_at'  => '2025-06-09 08:31:06',
                'updated_at'  => '2025-06-09 08:31:06',
            ],
            [
                'id'          => 44,
                'name'        => 'Latte Nóng',
                'description' => 'Một sự kết hợp tinh tế giữa vị đắng cà phê Espresso nguyên chất hòa quyện cùng vị sữa nóng ngọt ngào, bên trên là một lớp kem mỏng nhẹ tạo nên một tách cà phê hoàn hảo về hương vị lẫn nhãn quan.',
                'price'       => 59000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737357451_latte-nong_5072d19ea4af4c28a1f9f307e49d3af9.png',
                'category_id' => 10,
                'active'      => true,
                'created_at'  => '2025-06-09 08:31:58',
                'updated_at'  => '2025-06-09 08:31:58',
            ],
            [
                'id'          => 45,
                'name'        => 'Oolong Tứ Quý Dâu Trân Châu',
                'description' => 'Sảng khoái với vị dâu chín mọng chua thanh. Nền trà Oolong Tứ Quý đậm hương, ngọt thanh hậu vị. Thêm tận hưởng với trân châu trắng giòn dai.',
                'price'       => 49000,
                'price_sale'  => 49000,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737356372_oolong-tu-quy-dau_d9633516f6f84e5eab033a9155bc2f0b.png',
                'category_id' => 11,
                'active'      => true,
                'created_at'  => '2025-06-09 08:34:37',
                'updated_at'  => '2025-06-09 08:34:37',
            ],
            [
                'id'          => 46,
                'name'        => 'Oolong Tứ Quý Vải',
                'description' => 'Đậm hương trà, thanh mát sắc xuân với Oolong Tứ Quý Vải. Cảm nhận hương hoa đầu mùa, hòa quyện cùng vị vải chín mọng căng tràn sức sống.',
                'price'       => 49000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737356353_oolong-tu-quy-vai_f12d34a153334a7697360762675428fb.png',
                'category_id' => 11,
                'active'      => true,
                'created_at'  => '2025-06-09 08:35:36',
                'updated_at'  => '2025-06-09 08:35:36',
            ],
            [
                'id'          => 47,
                'name'        => 'Oolong Tứ Quý Kim Quất Trân Châu',
                'description' => 'Đậm hương trà, sảng khoái du xuân cùng Oolong Tứ Quý Kim Quất Trân Châu. Vị nước cốt kim quất tươi chua ngọt, thêm trân châu giòn dai.',
                'price'       => 49000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737356364_oolong-kim-quat-tran-chau_52e8184ea277407b8ec80e795316b47b.png',
                'category_id' => 11,
                'active'      => true,
                'created_at'  => '2025-06-09 08:36:13',
                'updated_at'  => '2025-06-09 08:36:13',
            ],
            [
                'id'          => 48,
                'name'        => 'Trà Sữa Oolong Nướng Sương Sáo',
                'description' => 'Tận hưởng hương vị Oolong nướng đậm đà được Nhà rang kỹ càng, quyện cùng sữa thơm béo, càng thêm hấp dẫn với sương sáo thanh mát.',
                'price'       => 55000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737356814_ts-oolong-nuong-suong-sao_4aed3eb72fa6456b9990580c54b51b78.png',
                'category_id' => 12,
                'active'      => true,
                'created_at'  => '2025-06-09 08:38:41',
                'updated_at'  => '2025-06-09 08:38:41',
            ],
            [
                'id'          => 49,
                'name'        => 'Hồng Trà Sữa Nóng',
                'description' => 'Từng ngụm trà chuẩn gu ấm áp, đậm đà beo béo bởi lớp sữa tươi chân ái hoà quyện. Trà đen nguyên lá âm ấm dịu nhẹ, quyện cùng lớp sữa thơm béo khó lẫn - hương vị ấm áp chuẩn gu trà, cho từng ngụm nhẹ nhàng, ngọt dịu lưu luyến mãi nơi cuống họng.',
                'price'       => 55000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737356747_hong-tra-sua-nong_48e7bdb6ef7b44f28b48412496150d26.png',
                'category_id' => 12,
                'active'      => true,
                'created_at'  => '2025-06-09 08:39:25',
                'updated_at'  => '2025-06-09 08:39:25',
            ],
            [
                'id'          => 50,
                'name'        => 'Hồng Trà Sữa Trân Châu',
                'description' => 'Thêm chút ngọt ngào cho ngày mới với hồng trà nguyên lá, sữa thơm ngậy được cân chỉnh với tỉ lệ hoàn hảo, cùng trân châu trắng dai giòn có sẵn để bạn tận hưởng từng ngụm trà sữa ngọt ngào thơm ngậy thiệt đã.',
                'price'       => 55000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737358261_hong-tra-sua-tran-chau_14cf4c6d514a4e76b52f641642d27e78.png',
                'category_id' => 12,
                'active'      => true,
                'created_at'  => '2025-06-09 08:40:07',
                'updated_at'  => '2025-06-09 08:40:07',
            ],
            [
                'id'          => 51,
                'name'        => 'Trà Sữa Oolong Tứ Quý Sương Sáo',
                'description' => 'Trà Oolong Tứ Quý ngạt ngào hoa cỏ mùa xuân, hòa quyện cùng sữa thơm mịn màng, sương sáo thanh mát. Đó là Lộc Yêu Yêu ngọt ngào mà Nhà gửi gắm đến bạn.',
                'price'       => 55000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737358275_tra-sua-oolong-tu-quy-suong-sao_57bb48cbbc4944079b58c9219d4d1ebf.png',
                'category_id' => 12,
                'active'      => true,
                'created_at'  => '2025-06-09 08:40:43',
                'updated_at'  => '2025-06-09 08:40:43',
            ],
            [
                'id'          => 52,
                'name'        => 'Mochi Kem Trà Sữa Trân Châu',
                'description' => 'Ngoài dẻo thơm, trong mát lạnh với kem vị trà sữa. Một cắn là say đắm, hai cắn là ngất ngây với trân châu giòn dai. *Bánh cần được bảo quản mát và dùng ngon nhất trong vòng 2 giờ sau khi nhận hàng.',
                'price'       => 19000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737355411_mochi-tra-sua_5950a2ce430440d5bbe33527b7e10021.png',
                'category_id' => 16,
                'active'      => true,
                'created_at'  => '2025-06-09 08:44:06',
                'updated_at'  => '2025-06-09 08:44:06',
            ],
            [
                'id'          => 53,
                'name'        => 'Mousse Tiramisu',
                'description' => 'Hương vị dễ ghiền được tạo nên bởi chút đắng nhẹ của cà phê, lớp kem trứng béo ngọt dịu hấp dẫn',
                'price'       => 35000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737355334_tiramisu_02b51263d15e419aa7da19528c369fa3.png',
                'category_id' => 16,
                'active'      => true,
                'created_at'  => '2025-06-09 08:44:54',
                'updated_at'  => '2025-06-09 08:44:54',
            ],
            [
                'id'          => 54,
                'name'        => 'Mochi Kem Việt Quất',
                'description' => 'Bao bọc bởi lớp vỏ Mochi dẻo thơm, bên trong là lớp kem lạnh cùng nhân việt quất đặc trưng thơm thơm, ngọt dịu. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.',
                'price'       => 19000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737355361_mochi-viet-quat_059d54c9074b4ad89f8a27eff9e3e709.png',
                'category_id' => 16,
                'active'      => true,
                'created_at'  => '2025-06-09 08:45:42',
                'updated_at'  => '2025-06-09 08:45:42',
            ],
            [
                'id'          => 55,
                'name'        => 'Mochi Kem Phúc Bồn Tử',
                'description' => 'Bao bọc bởi lớp vỏ Mochi dẻo thơm, bên trong là lớp kem lạnh cùng nhân phúc bồn tử ngọt ngào. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.',
                'price'       => 19000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737355355_mochi-phuc-bon-tu_ac9e0f60acbf43f89a7f6b1a0bcc743c.png',
                'category_id' => 16,
                'active'      => true,
                'created_at'  => '2025-06-09 08:46:11',
                'updated_at'  => '2025-06-09 08:46:11',
            ],
            [
                'id'          => 56,
                'name'        => 'Cà Phê Đen Đá Hộp (14 gói x 16g)',
                'description' => 'Cà Phê Đen Đá hoà tan với 100% hạt cà phê Robusta mang đến hương vị mạnh cực bốc, đậm đắng đầy lôi cuốn, đúng gu người Việt.',
                'price'       => 65000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737355913_cpg-cf-den-da_86b32f9f765b4501930928b6c9902bad.png',
                'category_id' => 17,
                'active'      => true,
                'created_at'  => '2025-06-09 08:47:20',
                'updated_at'  => '2025-06-09 08:47:20',
            ],
            [
                'id'          => 57,
                'name'        => 'Cà Phê Rang Xay Original 1 250G',
                'description' => 'Cà phê Original 1  với thành phần chính cà phê Robusta Đắk Lắk, vùng trồng cà phê nổi tiếng nhất Việt Nam. Bằng cách áp dụng kỹ thuật rang xay hiện đại, Cà phê Original 1 mang đến trải nghiệm tuyệt vời khi uống cà phê tại nhà với hương vị đậm đà truyền thống hợp khẩu vị của giới trẻ sành cà phê.',
                'price'       => 88000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737355876_cpg-cfrang-xay-original-1_c455a9b10e2b4a15a4dc891eddf10ca1.png',
                'category_id' => 17,
                'active'      => true,
                'created_at'  => '2025-06-09 08:49:35',
                'updated_at'  => '2025-06-09 08:49:35',
            ],
            [
                'id'          => 58,
                'name'        => 'Chocolate Nóng',
                'description' => 'Bột chocolate nguyên chất hoà cùng sữa tươi béo ngậy. Vị ngọt tự nhiên, không gắt cổ, để lại một chút đắng nhẹ, cay cay trên đầu lưỡi.',
                'price'       => 55000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737355571_chocolate-nong_c7331fe6900b403c83633a435f3527ac.png',
                'category_id' => 19,
                'active'      => true,
                'created_at'  => '2025-06-09 10:48:47',
                'updated_at'  => '2025-06-09 10:48:47',
            ],
            [
                'id'          => 59,
                'name'        => 'Matcha Latte Tây Bắc (Nóng)',
                'description' => 'Trà Xanh Latte (Nóng) là phiên bản rõ vị trà nhất. Nhấp một ngụm, bạn chạm ngay vị trà xanh Tây Bắc chát nhẹ hoà cùng sữa nguyên kem thơm béo, đọng lại hậu vị ngọt ngào, êm dịu. Không chỉ là thức uống tốt cho sức khoẻ, Trà Xanh Latte (Nóng) còn là cái ôm ấm áp của đồng bào Tây Bắc gửi cho người miền xuôi.',
                'price'       => 49000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737355604_tx-latte-nong_1de56d94ccf446b9ac8826653bef5842.png',
                'category_id' => 23,
                'active'      => true,
                'created_at'  => '2025-06-09 11:04:41',
                'updated_at'  => '2025-06-09 11:04:41',
            ],
            [
                'id'          => 60,
                'name'        => 'Matcha Latte Tây Bắc',
                'description' => 'Best seller của Nhà - rất phù hợp cho ai muốn nhập môn matcha. *Khuấy đều để thưởng trọn hương vị.',
                'price'       => 49000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737355612_tx-latte_6909ebc57c8e4b1e9aeef7e5ecdd5f9d.png',
                'category_id' => 23,
                'active'      => true,
                'created_at'  => '2025-06-09 11:05:36',
                'updated_at'  => '2025-06-09 11:05:36',
            ],
            [
                'id'          => 61,
                'name'        => 'Matcha Latte Tây Bắc Sữa Yến Mạch',
                'description' => 'Vị matcha êm mượt nhờ kết hợp với sữa yến mạch. *Khuấy đều để thưởng trọn hương vị.',
                'price'       => 49000,
                'price_sale'  => null,
                'image_url'   => 'https://product.hstatic.net/1000075078/product/1737355652_tx-latte-sym_6b3363267ba344719e7a15d3fb3893dc.png',
                'category_id' => 23,
                'active'      => true,
                'created_at'  => '2025-06-09 11:06:12',
                'updated_at'  => '2025-06-09 11:06:12',
            ],
        ];

        Product::insert($data);
    }
}
