<?php
namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class Users extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id'             => 1,
                'first_name'     => 'Thanh Tùng',
                'last_name'      => 'Lê',
                'gender'         => 'male',
                'date_of_birth'  => '2001-08-22',
                'mobile_no'      => '+84828035636',
                'email'          => 'iamrobotdiy@gmail.com',
                'active'         => 1,
                'remember_token' => null,
                'created_at'     => '2023-01-01 00:00:00',
                'updated_at'     => '2023-01-01 00:00:00',
            ],
            [
                'id'             => 2,
                'first_name'     => 'Minh Anh',
                'last_name'      => 'Nguyễn',
                'gender'         => 'female',
                'date_of_birth'  => '1998-05-15',
                'mobile_no'      => '+84987654321',
                'email'          => 'minhanh.nguyen@gmail.com',
                'active'         => 1,
                'remember_token' => null,
                'created_at'     => '2023-01-02 00:00:00',
                'updated_at'     => '2023-01-02 00:00:00',
            ],
            [
                'id'             => 3,
                'first_name'     => 'Hoàng',
                'last_name'      => 'Trần',
                'gender'         => 'male',
                'date_of_birth'  => '1995-11-30',
                'mobile_no'      => '+84912345678',
                'email'          => 'hoang.tran@gmail.com',
                'active'         => 1,
                'remember_token' => null,
                'created_at'     => '2023-01-03 00:00:00',
                'updated_at'     => '2023-01-03 00:00:00',
            ],
            [
                'id'             => 4,
                'first_name'     => 'Thảo',
                'last_name'      => 'Phạm',
                'gender'         => 'female',
                'date_of_birth'  => '2000-03-20',
                'mobile_no'      => '+84923456789',
                'email'          => 'thao.pham@gmail.com',
                'active'         => 1,
                'remember_token' => null,
                'created_at'     => '2023-01-04 00:00:00',
                'updated_at'     => '2023-01-04 00:00:00',
            ],
            [
                'id'             => 5,
                'first_name'     => 'Đức',
                'last_name'      => 'Lý',
                'gender'         => 'male',
                'date_of_birth'  => '1997-07-12',
                'mobile_no'      => '+84934567890',
                'email'          => 'duc.ly@gmail.com',
                'active'         => 0,
                'remember_token' => null,
                'created_at'     => '2023-01-05 00:00:00',
                'updated_at'     => '2023-01-05 00:00:00',
            ],
            [
                'id'             => 6,
                'first_name'     => 'Hương',
                'last_name'      => 'Đỗ',
                'gender'         => 'female',
                'date_of_birth'  => '1999-09-25',
                'mobile_no'      => '+84945678901',
                'email'          => 'huong.do@gmail.com',
                'active'         => 1,
                'remember_token' => null,
                'created_at'     => '2023-01-06 00:00:00',
                'updated_at'     => '2023-01-06 00:00:00',
            ],
            [
                'id'             => 7,
                'first_name'     => 'Tuấn',
                'last_name'      => 'Vũ',
                'gender'         => 'male',
                'date_of_birth'  => '1996-04-18',
                'mobile_no'      => '+84956789012',
                'email'          => 'tuan.vu@gmail.com',
                'active'         => 1,
                'remember_token' => null,
                'created_at'     => '2023-01-07 00:00:00',
                'updated_at'     => '2023-01-07 00:00:00',
            ],
            [
                'id'             => 8,
                'first_name'     => 'Linh',
                'last_name'      => 'Bùi',
                'gender'         => 'female',
                'date_of_birth'  => '2002-12-05',
                'mobile_no'      => '+84967890123',
                'email'          => 'linh.bui@gmail.com',
                'active'         => 1,
                'remember_token' => null,
                'created_at'     => '2023-01-08 00:00:00',
                'updated_at'     => '2023-01-08 00:00:00',
            ],
            [
                'id'             => 9,
                'first_name'     => 'Nam',
                'last_name'      => 'Đặng',
                'gender'         => 'male',
                'date_of_birth'  => '1994-06-28',
                'mobile_no'      => '+84978901234',
                'email'          => 'nam.dang@gmail.com',
                'active'         => 0,
                'remember_token' => null,
                'created_at'     => '2023-01-09 00:00:00',
                'updated_at'     => '2023-01-09 00:00:00',
            ],
            [
                'id'             => 10,
                'first_name'     => 'Mai',
                'last_name'      => 'Hoàng',
                'gender'         => 'female',
                'date_of_birth'  => '2003-02-14',
                'mobile_no'      => '+84989012345',
                'email'          => 'mai.hoang@gmail.com',
                'active'         => 1,
                'remember_token' => null,
                'created_at'     => '2023-01-10 00:00:00',
                'updated_at'     => '2023-01-10 00:00:00',
            ],
            [
                'id'             => 11,
                'first_name'     => 'Khôi',
                'last_name'      => 'Ngô',
                'gender'         => 'male',
                'date_of_birth'  => '1998-10-08',
                'mobile_no'      => '+84990123456',
                'email'          => 'khoi.ngo@gmail.com',
                'active'         => 1,
                'remember_token' => null,
                'created_at'     => '2023-01-11 00:00:00',
                'updated_at'     => '2023-01-11 00:00:00',
            ],
        ];
        User::insert($data);
    }
}
