name: Laravel CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /var/www/deploy-thecoffeeshop/theCoffeeBackend
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            find storage bootstrap/cache -type f -exec chmod 664 {} \;
            find storage bootstrap/cache -type d -exec chmod 775 {} \;

